library(readr)
se <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Balance_general/Educaci%C3%B3n/800019102.csv")
se2 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Balance_general/Educaci%C3%B3n/800040422.csv")
se3 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Balance_general/Educaci%C3%B3n/800172544.csv")
se4 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Balance_general/Educaci%C3%B3n/830033825.csv")
se5 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Balance_general/Educaci%C3%B3n/830040872.csv")
se6 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Balance_general/Educaci%C3%B3n/830096897.csv")
se7 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Balance_general/Educaci%C3%B3n/860058553.csv")
se8 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Balance_general/Educaci%C3%B3n/860511232.csv")
se9 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Balance_general/Educaci%C3%B3n/890913319.csv")
se10 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Balance_general/Educaci%C3%B3n/900088875.csv")
educación_BG <- cbind(se,se2,se3,se4,se5,se6,se7,se8,se9,se10)