library(readr)
sf1 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Estado_resultados/Servicios_financieros/800216181.csv")
sf2 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Estado_resultados/Servicios_financieros/805023971.csv")
sf3 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Estado_resultados/Servicios_financieros/811011779.csv")
sf4 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Estado_resultados/Servicios_financieros/811012271.csv")
sf5 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Estado_resultados/Servicios_financieros/830038885.csv")
sf6 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Estado_resultados/Servicios_financieros/830113598.csv")
sf7 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Estado_resultados/Servicios_financieros/860069163.csv")
sf8 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Estado_resultados/Servicios_financieros/900066708.csv")
sf9 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Estado_resultados/Servicios_financieros/900329769.csv")
sf10 <- read_csv("https://raw.githubusercontent.com/KellzGarcia/Sesiones_R/main/Estados%20Financieros/CSV/Estado_resultados/Servicios_financieros/900486584.csv")
financiero_ER <- cbind(sf1,sf2,sf3,sf4,sf5,sf6,sf7,sf8,sf9,sf10)